- name: "Upload letsencrypt_to_haproxy.sh"
  copy:
    src: "files/letsencrypt_to_haproxy.sh"
    dest: "/usr/local/bin/letsencrypt_to_haproxy.sh"
    mode: "0755"
    owner: "root"
    group: "root"
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Run certbot - Custom server and CA Bundle"
  when: item.value.custom_ca_bundle is defined
  shell: >
    REQUESTS_CA_BUNDLE={{ item.value.custom_ca_bundle }} \
    $(which certbot) certonly -n --webroot {{ item.value.extra_parameters | default('') }} \
      --server {{ item.value.custom_server }} \
      --agree-tos --email {{ item.value.agree_tos_email }} \
      --webroot-path {{ item.value.webroot }} \
      -d {{ item.value.domains | sort | join(' -d ') }}
  loop: "{{ common_utilities_acme_to_haproxy_items | dict2items }}"
  register: in_process_certbot_results_custom_ca
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Run certbot - Let's Encrypt"
  when: item.value.custom_ca_bundle is not defined
  shell: >
    $(which certbot) certonly -n --webroot {{ item.value.extra_parameters | default('') }} \
      --agree-tos --email {{ item.value.agree_tos_email }} \
      --webroot-path {{ item.value.webroot }} \
      -d {{ item.value.domains | sort | join(' -d ') }}
  loop: "{{ common_utilities_acme_to_haproxy_items | dict2items }}"
  register: in_process_certbot_results_letsencrypt
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Concatenate cert's into chain for haproxy - Let's Encrypt"
  shell: /usr/local/bin/letsencrypt_to_haproxy.sh
  tags:
  - "common_utilities"
  - "common_utilities_acme_to_haproxy"

- name: "Reload haproxy"
  service:
    name: "haproxy"
    state: "reloaded"
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"