- name: "Run certbot - Custom server and CA Bundle"
  when: item.value.custom_ca_bundle is defined
  shell: >
    REQUESTS_CA_BUNDLE={{ item.value.custom_ca_bundle }} \
    $(which certbot) certonly -n --webroot {{ item.value.extra_parameters | default('') }} \
      --server {{ item.value.custom_server }} \
      --agree-tos --email {{ item.value.agree_tos_email }} \
      --webroot-path {{ item.value.webroot }} \
      -d {{ item.value.domains | sort | join(' -d ') }}
  loop: "{{ common_utilities_acme_to_haproxy_items | dict2items }}"
  register: in_process_certbot_results_custom_ca
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Concatenate cert's into chain for haproxy - Custom server and CA Bundle"
  when: in_process_certbot_results_custom_ca.changed
  shell: "cat /etc/letsencrypt/live/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}/fullchain.pem /etc/letsencrypt/live/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}/privkey.pem > /etc/haproxy/certs/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}.pem"
  loop: "{{ in_process_certbot_results_custom_ca.results }}"
  register: in_process_haproxy_concatenate_custom_ca
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Run certbot - Let's Encrypt"
  when: item.value.custom_ca_bundle is not defined
  shell: >
    $(which certbot) certonly -n --webroot {{ item.value.extra_parameters | default('') }} \
      --agree-tos --email {{ item.value.agree_tos_email }} \
      --webroot-path {{ item.value.webroot }} \
      -d {{ item.value.domains | sort | join(' -d ') }}
  loop: "{{ common_utilities_acme_to_haproxy_items | dict2items }}"
  register: in_process_certbot_results_letsencrypt
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Concatenate cert's into chain for haproxy - Let's Encrypt"
  when: item.changed
  shell: "cat /etc/letsencrypt/live/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}/fullchain.pem /etc/letsencrypt/live/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}/privkey.pem > /etc/haproxy/certs/{{ item.stdout_lines | join('') | regex_search('\\b([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}\\b') }}.pem"
  loop: "{{ in_process_certbot_results_letsencrypt.results }}"
  register: in_process_haproxy_concatenate_letsencrypt
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Reload haproxy"
  when: in_process_haproxy_concatenate_custom_ca.changed or in_process_haproxy_concatenate_letsencrypt.changed
  service:
    name: "haproxy"
    state: "reloaded"
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"