- name: "Append listed groups to user."
  when:  item.1.enabled
  user:
    name: "{{ item.1.name }}"
    append: "yes"
    groups:  "{{ item.1.groups }}"
  loop: "{{ common_utilities_append_groups_to_user_items | default({}) | dictsort }}"
  tags:
    - common_utilities
    - common_utilities_append_groups_to_user