- name: "Append listed groups to user."
  when: item.value.enabled
  user:
    name: "{{ item.value.name }}"
    append: "yes"
    groups:  "{{ item.value.groups }}"
  loop: "{{ common_utilities_append_groups_to_user_items | default({}) | dict2items }}"
  tags:
    - common_utilities
    - common_utilities_append_groups_to_user