- name: "Upload a file"
  when:
    -  item.1.enabled
    -  item.1.delete == False
  copy:
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    mode: "{{ item.1.mode }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
  loop: "{{ common_utilities_certs | default({}) | dictsort }}"
  register: inprocess_upload_file
  tags:
    - "common_utilities"
    - "common_utilities_certs"

- name: "Delete a file"
  when:
    -  item.1.enabled
    -  item.1.delete == True
  file:
    state: "absent"
    dest: "{{ item.1.dest }}"
  loop: "{{ common_utilities_certs | default({}) | dictsort }}"
  register: inprocess_delete_file
  tags:
    - "common_utilities"
    - "common_utilities_certs"

- name: "Run update-ca-certificates when uploaded file is a CA cert"
  when:
    - inprocess_upload_file.changed
    - item.item.1.is_ca_cert
  shell: "{% if ansible_os_family == 'Debian' %}/usr/sbin/update-ca-certificates{% else %}/bin/update-ca-trust{% endif %}"
  loop: "{{ inprocess_upload_file.results | default([]) }}"
  tags:
    - "common_utilities"
    - "common_utilities_certs"

- name: "Run update-ca-certificates when deleted file is a CA cert"
  when:
    - inprocess_delete_file.changed
    - itme.item.1.is_ca_cert
  shell: "{% if ansible_os_family == 'Debian' %}/usr/sbin/update-ca-certificates{% else %}/bin/update-ca-trust{% endif %}"
  loop: "{{ inprocess_delete_file.results | default([]) }}"
  tags:
    - "common_utilities"
    - "common_utilities_certs"