---
- name: "Create directories"
  when:
    - item.value.enabled
    - item.value.delete == False
  file:
    state: "directory"
    dest: "{{ item.value.dest }}"
  loop: "{{ common_utilities_file_upload_directories | default({}) | dict2items }}"
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Delete directories"
  when:
    - item.value.enabled
    - item.value.delete == True
  file:
    state: "absent"
    dest: "{{ item.value.dest }}"
  loop: "{{ common_utilities_file_upload_directories | default({}) | dict2items }}"
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Upload a file"
  when:
    - item.value.enabled
    - item.value.delete == False
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    mode: "{{ item.value.mode }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
  loop: "{{ common_utilities_file_upload_items | default({}) | dict2items }}"
  register: inprocess_upload_file
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Delete a file"
  when:
    - item.value.enabled
    - item.value.delete == True
  file:
    state: "absent"
    dest: "{{ item.value.dest }}"
  loop: "{{ common_utilities_file_upload_items | default({}) | dict2items }}"
  register: inprocess_delete_file
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Run update-ca-certificates when uploaded file is a CA cert"
  when:
    - inprocess_upload_file.changed
    - item.item.value.is_ca_cert
  shell: update-ca-certificates
  loop: "{{ inprocess_upload_file.results | default([]) }}"
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Run update-ca-certificates when deleted file is a CA cert"
  when:
    - inprocess_delete_file.changed
    - item.item.value.is_ca_cert
  shell: update-ca-certificates
  loop: "{{ inprocess_delete_file.results | default([]) }}"
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

