- name: create htpasswd users - always run
  when:
    - common_utilities_htpasswd_enabled
    - ( item.1.run_once is not defined or item.1.run_once == false )
  #no_log: True
  run_once: false
  htpasswd:
    state: "{{ item.1.state }}"
    create: "yes"
    path: "{{ item.1.path }}"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt_scheme }}"
  loop: "{{ common_utilities_htpasswd_users | default({}) | dictsort }}"
  tags:
    - common_utilities
    - common_utilities_htpasswd

- name: create htpasswd users - run once
  when:
    - common_utilities_htpasswd_enabled
    - item.1.run_once is defined
    - item.1.run_once
  #no_log: True
  run_once: true
  htpasswd:
    state: "{{ item.1.state }}"
    create: "yes"
    path: "{{ item.1.path }}"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt_scheme }}"
  loop: "{{ common_utilities_htpasswd_users | default({}) | dictsort }}"
  tags:
    - common_utilities
    - common_utilities_htpasswd