- name: create htpasswd users
  when: common_utilities_htpasswd_enabled
  #no_log: True
  run_once: item.1.run_once | default(false)
  htpasswd:
    state: "{{ item.1.state }}"
    create: "yes"
    path: "{{ item.1.path }}"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt_scheme }}"
  loop: "{{ common_utilities_htpasswd_users | default({}) | dictsort }}"
  tags:
    - common_utilities
    - common_utilities_htpasswd