- name: "Include /etc/aliases tasks"
  when: common_utilities_etc_aliases_enabled
  include_tasks: etc_aliases.yml
  tags:
    - "common_utilities"
    - "common_utilities_etc_aliases"

- name: "Include file upload tasks."
  when: common_utilities_file_upload_enabled
  include_tasks: file_upload.yml
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Include docker tasks."
  when: common_utilities_docker_enable_enabled
        or common_utilities_docker_networking_enabled
        or common_utilities_docker_volumes_enabled
  include_tasks: docker.yml
  tags:
    - "common_utilities"
    - "common_utilities_docker"
    - "common_utilities_docker_enable"
    - "common_utilities_docker_networking"
    - "common_utilities_docker_volumes"

- name: "Include Append Groups to User tasks."
  when: common_utilities_append_groups_to_user_enabled
  include_tasks: append_groups_to_user.yml
  tags:
    - "common_utilities"
    - "common_utilities_append_groups_to_user"