- name: "Include /etc/aliases tasks"
  when: common_utilities_etc_aliases_enabled
  include_tasks: etc_aliases.yml
  tags:
    - "common_utilities"
    - "common_utilities_etc_aliases"

- name: "Include docker tasks."
  when: common_utilities_docker_enable_enabled
        or common_utilities_docker_networking_enabled
        or common_utilities_docker_volumes_enabled
  include_tasks: docker.yml
  tags:
    - "common_utilities"
    - "common_utilities_docker"
    - "common_utilities_docker_enable"
    - "common_utilities_docker_networking"
    - "common_utilities_docker_volumes"

- name: "Include Acme to HAProxy tasks."
  when: common_utilities_acme_to_haproxy_enabled
  include_tasks: acme_to_haproxy.yml
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Include git clone tasks."
  when: common_utilities_git_clone_enabled
  include_tasks: git_clone.yml
  tags:
    - "common_utilities"
    - "common_utilities_git_clone"

- name: "Include template etc/hosts tasks."
  when: common_utilities_template_etc_hosts_enabled
  include_tasks: template_etc_hosts.yml
  tags:
    - "common_utilities"
    - "common_utilities_etc_hosts"

- name: "Include disable core dump tasks."
  when:
    - common_utilities_disable_core_dumps_enabled
    - not common_utilities_enable_core_dumps_enabled
  include_tasks: disable_core_dumps.yml
  tags:
    - "common_utilities"
    - "common_utilities_disable_core_dumps"

- name: "Include enable core dump tasks."
  when:
    - common_utilities_enable_core_dumps_enabled
    - not common_utilities_disable_core_dumps_enabled
  include_tasks: enable_core_dumps.yml
  tags:
    - "common_utilities"
    - "common_utilities_enable_core_dumps"

- name: "Include apticron tasks"
  when:
    - common_utilities_apticron_enabled
    - ansible_pkg_mgr == 'apt'
  include_tasks: apticron.yml
  tags:
    - "common_utilities"
    - "common_utilities_apticron"