- name: "Include /etc/aliases tasks"
  when: common_utilities_etc_aliases_enabled
  include_tasks: etc_aliases.yml
  tags:
    - "common_utilities"
    - "common_utilities_etc_aliases"

- name: "Include file upload tasks."
  when: common_utilities_file_upload_enabled
  include_tasks: file_upload.yml
  tags:
    - "common_utilities"
    - "common_utilities_file_upload"

- name: "Include docker tasks."
  when: common_utilities_docker_enable_enabled
        or common_utilities_docker_networking_enabled
        or common_utilities_docker_volumes_enabled
  include_tasks: docker.yml
  tags:
    - "common_utilities"
    - "common_utilities_docker"
    - "common_utilities_docker_enable"
    - "common_utilities_docker_networking"
    - "common_utilities_docker_volumes"

- name: "Include Append Groups to User tasks."
  when: common_utilities_append_groups_to_user_enabled
  include_tasks: append_groups_to_user.yml
  tags:
    - "common_utilities"
    - "common_utilities_append_groups_to_user"

- name: "Include Acme to HAProxy tasks."
  when: common_utilities_acme_to_haproxy_enabled
  include_tasks: acme_to_haproxy.yml
  tags:
    - "common_utilities"
    - "common_utilities_acme_to_haproxy"

- name: "Include template_files tasks."
  when: common_utilities_template_files_enabled
  include_tasks: template_files.yml
  tags:
    - "common_utilities"
    - "common_utilities_template_files"
    - "common_utilities_template_files_yaml_filtered"
    - "common_utilities_template_files_non_filtered"

- name: "Include git clone tasks."
  when: common_utilities_git_clone_enabled
  include_tasks: git_clone.yml
  tags:
    - "common_utilities"
    - "common_utilities_git_clone"

- name: "Include template etc/hosts tasks."
  when: common_utilities_template_etc_hosts_enabled
  include_tasks: template_etc_hosts.yml
  tags:
    - "common_utilities"
    - "common_utilities_etc_hosts"