- name: "Template a non_filtered file."
  when:  item.1.enabled
  template:
    src: non_filtered.j2
    dest: "{{ item.1.target_path }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ common_utilities_template_files_non_filtered | dictsort }}"
  tags:
    - "common_utilities"
    - "common_utilities_template_files"
    - "common_utilities_template_files_non_filtered"

- name: "Template a yaml filtered file."
  when:  item.1.enabled
  template:
    src: yaml_filtered.j2
    dest: "{{ item.1.target_path }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ common_utilities_template_files_yaml_filtered | dictsort }}"
  tags:
    - "common_utilities"
    - "common_utilities_template_files"
    - "common_utilities_template_files_yaml_filtered"