- name: "Template /etc/hosts."
  template:
    src: etc_hosts.j2
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - "common_utilities"
    - "common_utilities_etc_hosts"